"""Tests for the Jinja2 new command module."""

from gentem.commands.new_jinja2 import (
    generate_class_name,
    generate_context,
    generate_slug,
    get_license_template_name,
    get_template_files,
)


class TestGenerateSlug:
    """Tests for generate_slug function."""

    def test_simple_name(self):
        """Test slug generation for simple names."""
        assert generate_slug("myproject") == "myproject"

    def test_with_underscores(self):
        """Test slug generation with underscores."""
        assert generate_slug("my_project") == "my-project"

    def test_with_spaces(self):
        """Test slug generation with spaces."""
        assert generate_slug("My Project") == "my-project"

    def test_mixed_case(self):
        """Test slug generation with mixed case."""
        assert generate_slug("MyProject") == "myproject"

    def test_multiple_spaces(self):
        """Test slug generation with multiple spaces."""
        assert generate_slug("My Awesome Project") == "my-awesome-project"


class TestGenerateClassName:
    """Tests for generate_class_name function."""

    def test_simple_name(self):
        """Test class name generation for simple names."""
        assert generate_class_name("myproject") == "Myproject"

    def test_with_underscores(self):
        """Test class name generation with underscores."""
        assert generate_class_name("my_project") == "MyProject"

    def test_mixed_case(self):
        """Test class name generation with mixed case."""
        assert generate_class_name("my_cool_project") == "MyCoolProject"


class TestGenerateContext:
    """Tests for generate_context function."""

    def test_library_context(self):
        """Test context generation for library project."""
        context = generate_context(
            project_name="mylib",
            project_type="library",
            author="John Doe",
            description="A test library",
            license_type="mit",
        )

        assert context["project_name"] == "mylib"
        assert context["project_slug"] == "mylib"
        assert context["class_name"] == "Mylib"
        assert context["author"] == "John Doe"
        assert context["email"] == "user@mylib.dev"
        assert context["description"] == "A test library"
        assert context["license"] == "MIT"
        assert context["library_enabled"] is True
        assert context["cli_enabled"] is False
        assert context["script_enabled"] is False

    def test_cli_context(self):
        """Test context generation for CLI project."""
        context = generate_context(
            project_name="mycli",
            project_type="cli",
            author="Jane Doe",
            description="",
            license_type="apache",
        )

        assert context["cli_enabled"] is True
        assert context["library_enabled"] is False
        assert context["script_enabled"] is False
        assert context["license"] == "APACHE"

    def test_script_context(self):
        """Test context generation for script project."""
        context = generate_context(
            project_name="myscript",
            project_type="script",
            author="",
            description="",
            license_type="bsd",
        )

        assert context["script_enabled"] is True
        assert context["library_enabled"] is False
        assert context["cli_enabled"] is False

    def test_default_author(self):
        """Test that default author is used when not provided."""
        context = generate_context(
            project_name="myproject",
            project_type="library",
            author="",
            description="",
            license_type="mit",
        )

        assert context["author"] == "Gentem User"

    def test_default_description(self):
        """Test that default description is used when not provided."""
        context = generate_context(
            project_name="myproject",
            project_type="cli",
            author="",
            description="",
            license_type="mit",
        )

        assert "cli project generated by Gentem" in context["description"]

    def test_email_generation(self):
        """Test that email is generated from project slug."""
        context = generate_context(
            project_name="My Test Project",
            project_type="library",
            author="Test",
            description="",
            license_type="mit",
        )

        assert context["email"] == "user@my-test-project.dev"

    def test_version_default(self):
        """Test that default version is set."""
        context = generate_context(
            project_name="myproject",
            project_type="library",
            author="",
            description="",
            license_type="mit",
        )

        assert context["version"] == "0.1.0"

    def test_python_versions(self):
        """Test that python versions are set correctly."""
        context = generate_context(
            project_name="myproject",
            project_type="library",
            author="",
            description="",
            license_type="mit",
        )

        assert context["python_version"] == "3.9"
        assert context["python_versions"] == ["3.10", "3.11", "3.12"]


class TestGetLicenseTemplateName:
    """Tests for get_license_template_name function."""

    def test_mit_license(self):
        """Test MIT license template name."""
        assert get_license_template_name("mit") == "license_mit"

    def test_apache_license(self):
        """Test Apache license template name."""
        assert get_license_template_name("apache") == "license_apache"

    def test_gpl_license(self):
        """Test GPL license template name."""
        assert get_license_template_name("gpl") == "license_gpl"

    def test_bsd_license(self):
        """Test BSD license template name."""
        assert get_license_template_name("bsd") == "license_bsd"

    def test_unknown_license_defaults_to_mit(self):
        """Test that unknown license defaults to MIT."""
        assert get_license_template_name("unknown") == "license_mit"
        assert get_license_template_name("") == "license_mit"

    def test_case_insensitive(self):
        """Test that license type is case insensitive."""
        assert get_license_template_name("MIT") == "license_mit"
        assert get_license_template_name("Apache") == "license_apache"


class TestGetTemplateFiles:
    """Tests for get_template_files function."""

    def test_library_files(self):
        """Test file list for library project."""
        files = get_template_files("library")

        assert ("base/gitignore.j2", ".gitignore") in files
        assert ("library/pyproject.toml.j2", "pyproject.toml") in files
        assert ("library/README.md.j2", "README.md") in files
        assert ("library/src/__init__.py.j2", "src/__init__.py") in files
        assert ("library/tests/__init__.py.j2", "tests/__init__.py") in files
        assert ("library/tests/test_core.py.j2", "tests/test_core.py") in files

    def test_cli_files(self):
        """Test file list for CLI project."""
        files = get_template_files("cli")

        assert ("base/gitignore.j2", ".gitignore") in files
        assert ("cli/pyproject.toml.j2", "pyproject.toml") in files
        assert ("cli/README.md.j2", "README.md") in files
        assert ("cli/src/__init__.py.j2", "src/__init__.py") in files
        assert ("cli/src/cli.py.j2", "src/cli.py") in files
        assert ("cli/src/main.py.j2", "src/main.py") in files

    def test_script_files(self):
        """Test file list for script project."""
        files = get_template_files("script")

        assert ("base/gitignore.j2", ".gitignore") in files
        assert ("script/__main__.py.j2", "__main__.py") in files
        # Script should NOT have pyproject.toml or tests
        assert not any("pyproject.toml" in f[1] for f in files)
        assert not any("tests/" in f[1] for f in files)

    def test_unknown_project_type(self):
        """Test that unknown project type returns only base files."""
        files = get_template_files("unknown")

        assert ("base/gitignore.j2", ".gitignore") in files
        assert len(files) == 1

    def test_all_files_have_jinja_extension(self):
        """Test that all template paths have .j2 extension."""
        for project_type in ["library", "cli", "script"]:
            files = get_template_files(project_type)
            for template_path, _ in files:
                assert template_path.endswith(".j2"), f"Missing .j2 extension: {template_path}"
