"""Tests for the Jinja2 FastAPI command module."""

from gentem.commands.fastapi_jinja2 import (
    generate_class_name,
    generate_context,
    generate_slug,
    get_template_files,
)


class TestGenerateSlug:
    """Tests for generate_slug function."""

    def test_simple_name(self):
        """Test slug generation for simple names."""
        assert generate_slug("myproject") == "myproject"

    def test_with_underscores(self):
        """Test slug generation with underscores."""
        assert generate_slug("my_project") == "my-project"

    def test_with_spaces(self):
        """Test slug generation with spaces."""
        assert generate_slug("My Project") == "my-project"

    def test_multiple_spaces(self):
        """Test slug generation with multiple spaces."""
        assert generate_slug("My API Project") == "my-api-project"


class TestGenerateClassName:
    """Tests for generate_class_name function."""

    def test_simple_name(self):
        """Test class name generation for simple names."""
        assert generate_class_name("myapi") == "Myapi"

    def test_with_underscores(self):
        """Test class name generation with underscores."""
        assert generate_class_name("my_api") == "MyApi"

    def test_mixed_case(self):
        """Test class name generation with mixed case."""
        assert generate_class_name("my_cool_api") == "MyCoolApi"


class TestGenerateContext:
    """Tests for generate_context function."""

    def test_basic_context(self):
        """Test basic context generation for FastAPI project."""
        context = generate_context(
            project_name="myapi",
            async_mode=False,
            db_type=None,
            author="John Doe",
            description="A test API",
        )

        assert context["project_name"] == "myapi"
        assert context["project_slug"] == "myapi"
        assert context["class_name"] == "Myapi"
        assert context["author"] == "John Doe"
        assert context["email"] == "user@myapi.dev"
        assert context["description"] == "A test API"
        assert context["async_mode"] is False
        assert context["db_type"] is None
        assert context["has_database"] is False

    def test_async_mode_context(self):
        """Test context generation with async mode enabled."""
        context = generate_context(
            project_name="myapi",
            async_mode=True,
            db_type=None,
            author="Jane Doe",
            description="",
        )

        assert context["async_mode"] is True
        assert context["has_database"] is False

    def test_database_context(self):
        """Test context generation with database."""
        context = generate_context(
            project_name="myapi",
            async_mode=True,
            db_type="asyncpg",
            author="Test Author",
            description="",
        )

        assert context["db_type"] == "asyncpg"
        assert context["has_database"] is True

    def test_sqlite_database_context(self):
        """Test context generation with SQLite database."""
        context = generate_context(
            project_name="myapi",
            async_mode=False,
            db_type="sqlite",
            author="",
            description="",
        )

        assert context["db_type"] == "sqlite"
        assert context["has_database"] is True
        assert context["async_mode"] is False

    def test_default_author(self):
        """Test that default author is used when not provided."""
        context = generate_context(
            project_name="myapi",
            async_mode=False,
            db_type=None,
            author="",
            description="",
        )

        assert context["author"] == "Gentem User"

    def test_default_description(self):
        """Test that default description is used when not provided."""
        context = generate_context(
            project_name="myapi",
            async_mode=False,
            db_type=None,
            author="",
            description="",
        )

        assert "FastAPI project generated by Gentem" in context["description"]

    def test_email_generation(self):
        """Test that email is generated from project slug."""
        context = generate_context(
            project_name="My Test API",
            async_mode=False,
            db_type=None,
            author="Test",
            description="",
        )

        assert context["email"] == "user@my-test-api.dev"

    def test_version_default(self):
        """Test that default version is set."""
        context = generate_context(
            project_name="myapi",
            async_mode=False,
            db_type=None,
            author="",
            description="",
        )

        assert context["version"] == "0.1.0"

    def test_python_versions(self):
        """Test that python versions are set correctly for FastAPI."""
        context = generate_context(
            project_name="myapi",
            async_mode=False,
            db_type=None,
            author="",
            description="",
        )

        assert context["python_version"] == "3.10"
        assert context["python_versions"] == ["3.10", "3.11", "3.12"]


class TestGetTemplateFiles:
    """Tests for get_template_files function."""

    def test_fastapi_without_database(self):
        """Test file list for FastAPI project without database."""
        files = get_template_files(has_database=False)

        # Core files should be present
        assert ("fastapi/pyproject.toml.j2", "pyproject.toml") in files
        assert ("fastapi/requirements.txt.j2", "requirements.txt") in files
        assert ("fastapi/.env.j2", ".env") in files
        assert ("fastapi/.gitignore.j2", ".gitignore") in files
        assert ("fastapi/README.md.j2", "README.md") in files

        # App structure
        assert ("fastapi/app/__init__.py.j2", "app/__init__.py") in files
        assert ("fastapi/app/main.py.j2", "app/main.py") in files
        assert ("fastapi/app/core/__init__.py.j2", "app/core/__init__.py") in files
        assert ("fastapi/app/core/config.py.j2", "app/core/config.py") in files
        assert ("fastapi/app/core/exceptions.py.j2", "app/core/exceptions.py") in files

        # V1 API
        assert ("fastapi/app/v1/__init__.py.j2", "app/v1/__init__.py") in files
        assert ("fastapi/app/v1/apis/__init__.py.j2", "app/v1/apis/__init__.py") in files
        assert ("fastapi/app/v1/apis/routes.py.j2", "app/v1/apis/routes.py") in files

        # Services, utils, schemas, models
        assert ("fastapi/app/services/__init__.py.j2", "app/services/__init__.py") in files
        assert ("fastapi/app/utils/__init__.py.j2", "app/utils/__init__.py") in files
        assert ("fastapi/app/schemas/__init__.py.j2", "app/schemas/__init__.py") in files
        assert ("fastapi/app/models/__init__.py.j2", "app/models/__init__.py") in files
        assert ("fastapi/app/deps/__init__.py.j2", "app/deps/__init__.py") in files

        # Database file should NOT be present
        assert not any("database.py" in f[1] for f in files)

    def test_fastapi_with_database(self):
        """Test file list for FastAPI project with database."""
        files = get_template_files(has_database=True)

        # Database file should be present
        assert ("fastapi/app/core/database.py.j2", "app/core/database.py") in files

    def test_all_files_have_jinja_extension(self):
        """Test that all template paths have .j2 extension."""
        for has_database in [True, False]:
            files = get_template_files(has_database=has_database)
            for template_path, _ in files:
                assert template_path.endswith(".j2"), f"Missing .j2 extension: {template_path}"

    def test_core_files_present(self):
        """Test that core FastAPI files are always present."""
        files_no_db = get_template_files(has_database=False)
        files_with_db = get_template_files(has_database=True)

        # Both should have these core files
        core_files = [
            "pyproject.toml",
            "requirements.txt",
            ".env",
            ".gitignore",
            "README.md",
            "app/__init__.py",
            "app/main.py",
            "app/core/config.py",
            "app/core/exceptions.py",
        ]

        for filename in core_files:
            assert any(f[1] == filename for f in files_no_db), f"Missing {filename} in no-db config"
            assert any(f[1] == filename for f in files_with_db), f"Missing {filename} in db config"
