"""Implementation of the `gentem fastapi` command using Jinja2 templates."""

from datetime import datetime
from pathlib import Path
from typing import Any, Optional

from rich import print
from rich.panel import Panel

from gentem.template_engine import TemplateEngine
from gentem.utils.validators import (
    ValidationError,
    validate_db_type,
    validate_project_name,
)


def generate_slug(name: str) -> str:
    """Generate a URL-safe slug from the project name."""
    return name.lower().replace("_", "-").replace(" ", "-")


def generate_class_name(name: str) -> str:
    """Generate a Python class name from the project name."""
    return "".join(word.capitalize() for word in name.split("_"))


def generate_context(
    project_name: str,
    async_mode: bool,
    db_type: Optional[str],
    author: str,
    description: str,
) -> dict[str, Any]:
    """Generate the template context for a FastAPI project.

    Args:
        project_name: Name of the project.
        async_mode: Whether to use async mode.
        db_type: Database type (asyncpg, etc.).
        author: Author name.
        description: Project description.

    Returns:
        Dictionary of template variables.
    """
    now = datetime.now()
    slug = generate_slug(project_name)

    return {
        "project_name": project_name,
        "project_slug": slug,
        "class_name": generate_class_name(project_name),
        "author": author or "Gentem User",
        "email": f"user@{slug}.dev",
        "description": description or "A FastAPI project generated by Gentem.",
        "version": "0.1.0",
        "python_version": "3.10",
        "python_versions": ["3.10", "3.11", "3.12"],
        "async_mode": async_mode,
        "db_type": db_type,
        "has_database": db_type is not None,
        "year": now.year,
        "month": now.strftime("%B"),
    }


def get_template_files(has_database: bool) -> list[tuple[str, str]]:
    """Get list of template files to render for a FastAPI project.

    Args:
        has_database: Whether database support is included.

    Returns:
        List of (template_path, output_path) tuples.
    """
    templates = [
        ("fastapi/pyproject.toml.j2", "pyproject.toml"),
        ("fastapi/requirements.txt.j2", "requirements.txt"),
        ("fastapi/.env.j2", ".env"),
        ("fastapi/.gitignore.j2", ".gitignore"),
        ("fastapi/README.md.j2", "README.md"),
        ("fastapi/app/__init__.py.j2", "app/__init__.py"),
        ("fastapi/app/main.py.j2", "app/main.py"),
        ("fastapi/app/core/__init__.py.j2", "app/core/__init__.py"),
        ("fastapi/app/core/config.py.j2", "app/core/config.py"),
        ("fastapi/app/core/exceptions.py.j2", "app/core/exceptions.py"),
        ("fastapi/app/deps/__init__.py.j2", "app/deps/__init__.py"),
        ("fastapi/app/utils/__init__.py.j2", "app/utils/__init__.py"),
        ("fastapi/app/v1/__init__.py.j2", "app/v1/__init__.py"),
        ("fastapi/app/v1/apis/__init__.py.j2", "app/v1/apis/__init__.py"),
        ("fastapi/app/v1/apis/routes.py.j2", "app/v1/apis/routes.py"),
        ("fastapi/app/services/__init__.py.j2", "app/services/__init__.py"),
        ("fastapi/app/schemas/__init__.py.j2", "app/schemas/__init__.py"),
        ("fastapi/app/models/__init__.py.j2", "app/models/__init__.py"),
    ]

    if has_database:
        templates.append(("fastapi/app/core/database.py.j2", "app/core/database.py"))

    return templates


def create_fastapi_project(
    project_name: str,
    async_mode: bool = False,
    db_type: str = "",
    author: str = "",
    description: str = "",
    dry_run: bool = False,
    verbose: bool = False,
) -> None:
    """Create a new FastAPI project using Jinja2 templates.

    Args:
        project_name: Name of the project to create.
        async_mode: Use async mode with lifespan.
        db_type: Database type (asyncpg for async SQLAlchemy).
        author: Author name.
        description: Project description.
        dry_run: Preview without creating files.
        verbose: Show verbose output.
    """
    # Validate inputs
    try:
        project_name = validate_project_name(project_name)
        db_type = validate_db_type(db_type)
    except ValidationError as e:
        print(f"[red]Error: {e}[/]")
        raise SystemExit(1) from e

    # Generate template context
    context = generate_context(
        project_name=project_name,
        async_mode=async_mode,
        db_type=db_type,
        author=author,
        description=description,
    )

    # Determine output path
    output_path = Path.cwd() / context["project_slug"]

    if verbose:
        print(f"Output path: {output_path}")
        print(f"Async mode: {async_mode}")
        print(f"Database type: {db_type or 'none'}")

    # Show summary
    db_info = f"Database: {db_type}" if db_type else "No database"
    print(
        Panel(
            f"[bold]Creating new FastAPI project:[/] [cyan]{project_name}[/]\n"
            f"[dim]Async:[/] {str(async_mode)} | [dim]{db_info}[/]\n"
            f"[dim]Author:[/] {context['author']}",
            title="Gentem (Jinja2)",
            expand=False,
        )
    )

    if dry_run:
        print("[yellow]DRY RUN - No files will be created[/]")
        print(f"\nProject would be created at: {output_path}")
        print("\nFiles that would be created:")
        for template_path, _ in get_template_files(db_type is not None):
            print(f"  - {template_path}")
        return

    # Initialize template engine
    engine = TemplateEngine()

    # Create project directory
    try:
        output_path.mkdir(parents=True, exist_ok=False)
    except FileExistsError:
        print(f"[red]Error: Directory '{output_path}' already exists[/]")
        raise SystemExit(1) from FileExistsError

    # Render and write files
    try:
        for template_path, output_file in get_template_files(db_type is not None):
            content = engine.render_template(template_path, context)
            file_path = output_path / output_file
            file_path.parent.mkdir(parents=True, exist_ok=True)
            file_path.write_text(content, encoding="utf-8")

        print(f"\n[green]✓ FastAPI project '{context['project_slug']}' created successfully![/]")
        print("\nNext steps:")
        print(f"  cd {context['project_slug']}")
        print("  pip install -r requirements.txt")
        print(f"  uvicorn {context['project_slug']}.main:app --reload")

    except Exception as e:
        print(f"[red]Error creating project: {e}[/]")
        # Clean up created directory
        if output_path.exists():
            import shutil
            shutil.rmtree(output_path)
        raise SystemExit(1) from e
