"""Implementation of the `gentem new` command using Jinja2 templates."""

from datetime import datetime
from pathlib import Path
from typing import Any

from rich import print
from rich.panel import Panel

from gentem.template_engine import TemplateEngine
from gentem.utils.validators import (
    ValidationError,
    validate_license_type,
    validate_project_name,
    validate_project_type,
)


def generate_slug(name: str) -> str:
    """Generate a URL-safe slug from the project name."""
    return name.lower().replace("_", "-").replace(" ", "-")


def generate_class_name(name: str) -> str:
    """Generate a Python class name from the project name."""
    return "".join(word.capitalize() for word in name.split("_"))


def generate_context(
    project_name: str,
    project_type: str,
    author: str,
    description: str,
    license_type: str,
) -> dict[str, Any]:
    """Generate the template context for a new project.

    Args:
        project_name: Name of the project.
        project_type: Type of project (library, cli, script).
        author: Author name.
        description: Project description.
        license_type: License type.

    Returns:
        Dictionary of template variables.
    """
    now = datetime.now()
    year = now.year

    return {
        "project_name": project_name,
        "project_slug": generate_slug(project_name),
        "class_name": generate_class_name(project_name),
        "project_type": project_type,
        "author": author or "Gentem User",
        "email": f"user@{generate_slug(project_name)}.dev",
        "description": description or f"A {project_type} project generated by Gentem.",
        "version": "0.1.0",
        "python_version": "3.9",
        "python_versions": ["3.10", "3.11", "3.12"],
        "license": license_type.upper() if license_type else "MIT",
        "year": year,
        "month": now.strftime("%B"),
        "cli_enabled": project_type == "cli",
        "library_enabled": project_type == "library",
        "script_enabled": project_type == "script",
    }


def get_license_template_name(license_type: str) -> str:
    """Get the license template name based on type.

    Args:
        license_type: Type of license.

    Returns:
        Template filename for the license.
    """
    license_type = license_type.lower()
    name_map = {
        "mit": "license_mit",
        "apache": "license_apache",
        "gpl": "license_gpl",
        "bsd": "license_bsd",
    }
    return name_map.get(license_type, "license_mit")


def get_template_files(project_type: str) -> list[tuple[str, str]]:
    """Get list of template files to render for a project type.

    Args:
        project_type: Type of project.

    Returns:
        List of (template_path, output_path) tuples.
    """
    base_templates = [
        ("base/gitignore.j2", ".gitignore"),
    ]

    if project_type == "library":
        project_files = [
            ("library/pyproject.toml.j2", "pyproject.toml"),
            ("library/README.md.j2", "README.md"),
            ("library/src/__init__.py.j2", "src/__init__.py"),
            ("library/tests/__init__.py.j2", "tests/__init__.py"),
            ("library/tests/test_core.py.j2", "tests/test_core.py"),
        ]
    elif project_type == "cli":
        project_files = [
            ("cli/pyproject.toml.j2", "pyproject.toml"),
            ("cli/README.md.j2", "README.md"),
            ("cli/src/__init__.py.j2", "src/__init__.py"),
            ("cli/src/cli.py.j2", "src/cli.py"),
            ("cli/src/main.py.j2", "src/main.py"),
        ]
    elif project_type == "script":
        project_files = [
            ("script/__main__.py.j2", "__main__.py"),
        ]
    else:
        project_files = []

    return base_templates + project_files


def create_new_project(
    project_name: str,
    project_type: str = "library",
    author: str = "",
    description: str = "",
    license_type: str = "mit",
    dry_run: bool = False,
    verbose: bool = False,
) -> None:
    """Create a new Python project using Jinja2 templates.

    Args:
        project_name: Name of the project to create.
        project_type: Type of project (library, cli, script).
        author: Author name.
        description: Project description.
        license_type: License type.
        dry_run: Preview without creating files.
        verbose: Show verbose output.
    """
    # Validate inputs
    try:
        project_name = validate_project_name(project_name)
        project_type = validate_project_type(project_type)
        license_type = validate_license_type(license_type)
    except ValidationError as e:
        print(f"[red]Error: {e}[/]")
        raise SystemExit(1) from e

    # Generate template context
    context = generate_context(
        project_name=project_name,
        project_type=project_type,
        author=author,
        description=description,
        license_type=license_type,
    )

    # Determine output path
    output_path = Path.cwd() / context["project_slug"]

    if verbose:
        print(f"Output path: {output_path}")
        print(f"Project type: {project_type}")

    # Show summary
    print(
        Panel(
            f"[bold]Creating new {project_type} project:[/] [cyan]{project_name}[/]\n"
            f"[dim]Author:[/] {context['author']}\n"
            f"[dim]License:[/] {context['license']}\n"
            f"[dim]Python:[/] {', '.join(context['python_versions'])}",
            title="Gentem (Jinja2)",
            expand=False,
        )
    )

    if dry_run:
        print("[yellow]DRY RUN - No files will be created[/]")
        print(f"\nProject would be created at: {output_path}")
        print("\nFiles that would be created:")
        for template_path, _ in get_template_files(project_type):
            print(f"  - {template_path}")
        return

    # Initialize template engine
    engine = TemplateEngine()

    # Get license template
    license_template_name = get_license_template_name(license_type)
    license_template_path = f"base/{license_template_name}.j2"

    # Create project directory
    try:
        output_path.mkdir(parents=True, exist_ok=False)
    except FileExistsError:
        print(f"[red]Error: Directory '{output_path}' already exists[/]")
        raise SystemExit(1) from FileExistsError

    # Render and write files
    try:
        # Render license template
        if license_type != "none":
            license_content = engine.render_template(license_template_path, context)
            (output_path / "LICENSE").write_text(license_content, encoding="utf-8")

        # Render project-specific templates
        for template_path, output_file in get_template_files(project_type):
            content = engine.render_template(template_path, context)
            file_path = output_path / output_file
            file_path.parent.mkdir(parents=True, exist_ok=True)
            file_path.write_text(content, encoding="utf-8")

        print(f"\n[green]✓ Project '{context['project_slug']}' created successfully![/]")
        print("\nNext steps:")
        print(f"  cd {context['project_slug']}")
        if project_type == "library":
            print("  pip install -e .")
        elif project_type == "cli":
            print("  pip install -e .")
            print(f"  {context['project_slug']} --help")
        print("  git init")

    except Exception as e:
        print(f"[red]Error creating project: {e}[/]")
        # Clean up created directory
        if output_path.exists():
            import shutil

            shutil.rmtree(output_path)
        raise SystemExit(1) from e
